--- 

- hosts: cluster
  remote_user: root

  tasks:

    - name: Get the command information to later join the node
      command: kubeadm token create --print-join-command
      register: kubernetes_join_command_result
    - set_fact: join_command={{ kubernetes_join_command_result.stdout }}
    - debug: msg="{{ join_command }}"

- hosts: nodes
  remote_user: root

  tasks:
    # Install base packages
    include: base.yaml

    include: install_k8_node.yaml
